apiVersion: v1
kind: Pod
metadata:
  name: spambot
  labels:
    spam: delicious
spec:
  containers:
  - name: spambot
    image: mewse/spambot:latest
    env:
    - name: TARGET_URL
      value: "http://10.43.0.96:30001/spam"
    - name: PORT
      value: "30000"
---
apiVersion: v1
kind: Pod
metadata:
  name: spambot2
  labels:
    spam: yumbles
spec:
  containers:
  - name: spambot
    image: mewse/spambot:latest
    env:
    - name: TARGET_URL
      value: "http://10.43.0.96:30000/spam"
    - name: PORT
      value: "30001"
