apiVersion: v1
kind: Service
metadata:
  name: spambot-svc
spec:
  ports:
  - name: rest
    nodePort: 30000
    port: 30000
  type: NodePort
  selector:
    spam: delicious

---
apiVersion: v1
kind: Service
metadata:
  name: spambot-svc2
spec:
  ports:
  - name: rest
    nodePort: 30001
    port: 30001
  type: NodePort
  selector:
    spam: yumbles

